"""initial

Revision ID: 65c06dc4b29a
Revises: 3ed0548a5b55
Create Date: 2026-05-15 21:44:03.354220

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '65c06dc4b29a'
down_revision: Union[str, Sequence[str], None] = '3ed0548a5b55'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('audit_log', sa.Column('id', sa.Integer(), autoincrement=True, nullable=False))
    op.add_column('audit_log', sa.Column('user_id', sa.Integer(), nullable=True))
    op.add_column('audit_log', sa.Column('Actions', sa.Text(), nullable=False))
    op.add_column('audit_log', sa.Column('Target', sa.Text(), nullable=False))
    op.add_column('audit_log', sa.Column('Outcome', sa.Text(), nullable=False))
    op.alter_column('audit_log', 'log_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               nullable=True)
    op.create_foreign_key(None, 'audit_log', 'users', ['user_id'], ['id'])
    op.drop_column('audit_log', 'actions')
    op.drop_column('audit_log', 'outcome')
    op.drop_column('audit_log', 'target')
    op.drop_column('audit_log', 'id_log')
    op.drop_column('audit_log', 'id_user')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('audit_log', sa.Column('id_user', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('audit_log', sa.Column('id_log', sa.INTEGER(), autoincrement=True, nullable=False))
    op.add_column('audit_log', sa.Column('target', sa.TEXT(), autoincrement=False, nullable=False))
    op.add_column('audit_log', sa.Column('outcome', sa.TEXT(), autoincrement=False, nullable=False))
    op.add_column('audit_log', sa.Column('actions', sa.TEXT(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'audit_log', type_='foreignkey')
    op.alter_column('audit_log', 'log_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.drop_column('audit_log', 'Outcome')
    op.drop_column('audit_log', 'Target')
    op.drop_column('audit_log', 'Actions')
    op.drop_column('audit_log', 'user_id')
    op.drop_column('audit_log', 'id')
    # ### end Alembic commands ###
